CREATE TABLE [dbo].AppsEarningsHistory (
    [AppIdentifier]                                 VARCHAR (50)    NOT NULL,
    [AppProgCompletedInTheYearInput]                BIT             NULL,
    [BalancingProgAimPaymentsInTheYear]             DECIMAL (12, 5) NULL,
    [CollectionYear]                                VARCHAR (4)     NOT NULL,
    [CollectionReturnCode]                          VARCHAR (3)     NOT NULL,
    [CompletionProgaimPaymentsInTheYear]            DECIMAL (12, 5) NULL,
    [DaysInYear]                                    INT             NULL,
    [FworkCode]                                     INT             NULL,
    [HistoricEffectiveTNPStartDateInput]            DATE            NULL,
    [HistoricLearner1618StartInput]                 BIT             NULL,
    [HistoricTotal1618UpliftPaymentsInTheYearInput] DECIMAL (12, 5) NULL,
    [HistoricTNP1Input]                             DECIMAL (12, 5) NULL,
    [HistoricTNP2Input]                             DECIMAL (12, 5) NULL,
    [HistoricTNP3Input]                             DECIMAL (12, 5) NULL,
    [HistoricTNP4Input]                             DECIMAL (12, 5) NULL,
    [HistoricVirtualTNP3EndOfTheYearInput]          DECIMAL (12, 5) NULL,
    [HistoricVirtualTNP4EndOfTheYearInput]          DECIMAL (12, 5) NULL,
    [LatestInYear]                                  BIT             NOT NULL,
    [LearnRefNumber]                                VARCHAR (12)    NOT NULL,
    [OnProgProgAimPaymentsInTheYear]                DECIMAL (12, 5) NULL,
    [ProgrammeStartDateIgnorePathway]               DATE            NULL,
    [ProgrammeStartDateMatchPathway]                DATE            NULL,
    [ProgType]                                      INT             NULL,
    [PwayCode]                                      INT             NULL,
    [STDCode]                                       INT             NULL,
    [TotalProgAimPaymentsInTheYear]                 DECIMAL (12, 5) NULL,
    [UptoEndDate]                                   DATE            NULL,
    [UKPRN]                                         INT             NOT NULL,
    [ULN]                                           BIGINT          NOT NULL,
    [HistoricEmpIdEndWithinYear]                    INT             NULL,
    [HistoricEmpIdStartWithinYear]                  INT             NULL,
    [HistoricPMRAmount]                             DECIMAL (12, 5) NULL,
    [HistoricLearnDelProgEarliestACT2DateInput]     DATE            NULL,
    CONSTRAINT [PK_Dbo_AppsEarningsHistory] PRIMARY KEY CLUSTERED ([LatestInYear] DESC, [LearnRefNumber] ASC, [UKPRN] ASC, [CollectionYear] ASC, [CollectionReturnCode] ASC, [AppIdentifier] ASC)
);

