//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.Data.AppsEarningsHistory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppsEarningsHistory
    {
        public string AppIdentifier { get; set; }
        public Nullable<bool> AppProgCompletedInTheYearInput { get; set; }
        public Nullable<decimal> BalancingProgAimPaymentsInTheYear { get; set; }
        public string CollectionYear { get; set; }
        public string CollectionReturnCode { get; set; }
        public Nullable<decimal> CompletionProgaimPaymentsInTheYear { get; set; }
        public Nullable<int> DaysInYear { get; set; }
        public Nullable<int> FworkCode { get; set; }
        public Nullable<System.DateTime> HistoricEffectiveTNPStartDateInput { get; set; }
        public Nullable<bool> HistoricLearner1618StartInput { get; set; }
        public Nullable<decimal> HistoricTotal1618UpliftPaymentsInTheYearInput { get; set; }
        public Nullable<decimal> HistoricTNP1Input { get; set; }
        public Nullable<decimal> HistoricTNP2Input { get; set; }
        public Nullable<decimal> HistoricTNP3Input { get; set; }
        public Nullable<decimal> HistoricTNP4Input { get; set; }
        public Nullable<decimal> HistoricVirtualTNP3EndOfTheYearInput { get; set; }
        public Nullable<decimal> HistoricVirtualTNP4EndOfTheYearInput { get; set; }
        public bool LatestInYear { get; set; }
        public string LearnRefNumber { get; set; }
        public Nullable<decimal> OnProgProgAimPaymentsInTheYear { get; set; }
        public Nullable<System.DateTime> ProgrammeStartDateIgnorePathway { get; set; }
        public Nullable<System.DateTime> ProgrammeStartDateMatchPathway { get; set; }
        public Nullable<int> ProgType { get; set; }
        public Nullable<int> PwayCode { get; set; }
        public Nullable<int> STDCode { get; set; }
        public Nullable<decimal> TotalProgAimPaymentsInTheYear { get; set; }
        public Nullable<System.DateTime> UptoEndDate { get; set; }
        public int UKPRN { get; set; }
        public long ULN { get; set; }
        public Nullable<int> HistoricEmpIdEndWithinYear { get; set; }
        public Nullable<int> HistoricEmpIdStartWithinYear { get; set; }
        public Nullable<decimal> HistoricPMRAmount { get; set; }
        public Nullable<System.DateTime> HistoricLearnDelProgEarliestACT2DateInput { get; set; }
    }
}
